### ISSUE TITLE
rainbird_tool.py doesn't work with ESP-TM2

### ISSUE THREAD

**Issue by donsilvia** [allenporter/pyrainbird#224]
I have an ESP-TM2 controller that I'm using with the Rainbird Android app.  I installed the latest pyrainbird from PyPi (2.0.0 ).  When I try to use rainbird_tool.py I get this error:

(rainbird) rainbird $ export RAINBIRD_SERVER=10.0.0.95
(rainbird) rainbird $ export RAINBIRD_PASSWORD=XXXXXXXX
(rainbird) rainbird $ ./rainbird_tool.py get_model_and_version
Traceback (most recent call last):
  File "/d0/dev/PycharmProjects/rainbird/./rainbird_tool.py", line 109, in <module>
    asyncio.run(main())
  File "/d0/apps/miniconda3/envs/rainbird/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/d0/apps/miniconda3/envs/rainbird/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/d0/dev/PycharmProjects/rainbird/./rainbird_tool.py", line 103, in main
    result = await args.func(client, **method_args)
  File "/d0/apps/miniconda3/envs/rainbird/lib/python3.10/site-packages/pyrainbird/async_client.py", line 164, in get_model_and_version
    response = await self._cacheable_command(
  File "/d0/apps/miniconda3/envs/rainbird/lib/python3.10/site-packages/pyrainbird/async_client.py", line 492, in _cacheable_command
    result = await self._process_command(funct, command, *args)
  File "/d0/apps/miniconda3/envs/rainbird/lib/python3.10/site-packages/pyrainbird/async_client.py", line 467, in _process_command
    decrypted_data = await self._tunnelSip(
  File "/d0/apps/miniconda3/envs/rainbird/lib/python3.10/site-packages/pyrainbird/async_client.py", line 454, in _tunnelSip
    result = await self._local_client.request(
AttributeError: 'tuple' object has no attribute 'request'

**Comment by allenporter** [comment]
Thanks for the report. The fix is in 3.0.1
