### ISSUE TITLE
Rainbird RC2 controller with build in wifi module

### ISSUE THREAD

**Issue by JacekKac** [allenporter/pyrainbird#300]
Hi. i am trying to run the example script and i get errors, not sure if this is connected to authentication or the RC2 is not supported. 
```

pi@HOME:~/pyrainbird/examples $ ./rainbird_tool.py --log-level debug get_wifi_params
Traceback (most recent call last):
  File "/home/pi/pyrainbird/examples/./rainbird_tool.py", line 109, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/pyrainbird/examples/./rainbird_tool.py", line 93, in main
    host = os.environ["RAINBIRD_SERVER"]
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RAINBIRD_SERVER'

```

**Comment by JacekKac** [comment]
eh sorry, forgot to export te variables
