### ISSUE TITLE
Rainbird RC2 controller with build in wifi module

### ISSUE THREAD

**Issue by JacekKac** [allenporter/pyrainbird#301]
Password seems to be OK, double checked. Any chance to get it working ?

```
pi@HOME:~/pyrainbird/examples $ sudo ./rainbird_tool.py --log-level debug get_wifi_params
DEBUG:pyrainbird.async_client:Request: {"id": 1700312162.342751, "jsonrpc": "2.0", "method": "getWifiParams", "params": {}}
/usr/local/lib/python3.9/dist-packages/aiohttp-4.0.0a1-py3.9-linux-armv7l.egg/aiohttp/client_reqrep.py:883: RuntimeWarning: coroutine 'noop' was never awaited
  self.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyrainbird-4.0.0-py3.9.egg/pyrainbird/async_client.py", line 134, in request
  File "/usr/local/lib/python3.9/dist-packages/aiohttp-4.0.0a1-py3.9-linux-armv7l.egg/aiohttp/client_reqrep.py", line 884, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Password', url=URL('http://192.168.1.49/stick')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/pyrainbird/examples/./rainbird_tool.py", line 110, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/pyrainbird/examples/./rainbird_tool.py", line 104, in main
    result = await args.func(client, **method_args)
  File "/usr/local/lib/python3.9/dist-packages/pyrainbird-4.0.0-py3.9.egg/pyrainbird/async_client.py", line 248, in get_wifi_params
  File "/usr/local/lib/python3.9/dist-packages/pyrainbird-4.0.0-py3.9.egg/pyrainbird/async_client.py", line 141, in request
pyrainbird.exceptions.RainbirdAuthException: Rain Bird device denied authentication; Incorrect Password?

```

**Comment by allenporter** [comment]
It's all known working for me, so not sure what the problem is for you.

You could also consider reviewing
https://github.com/allenporter/pyrainbird/blob/main/CONTRIBUTING.md and setting up a mitmproxy and capturing traffic from other sources like the app and confirm it can be decoded.

(See discussion in #178)

**Comment by JacekKac** [comment]
ok it's working instead of using password / host varables from system variables i put them into the code, but miss all places, reverted it back to system variables resolved the issue
